# Generated by Django 5.2 on 2025-06-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplehouse', '0002_sharerecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('txnid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50)),
                ('amt', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
    ]
